compiler = g++
output = bin/SilentEngine
maths = src/SilentMaths/*
renderer = src/SilentRenderer/*
entities = src/SilentEntities/*
system = src/SilentSystem/*
test = src/test.cpp
src = $(maths) $(renderer) $(entities) $(system) $(test)
all:
	$(compiler) $(src) -o $(output)
